version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  data_pipeline_file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: logs/finance-plan-pipeline.log

  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: default
    filename: logs/errors.log

  bronze_file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: logs/bronze_layer.log

  silver_file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: logs/silver_layer.log

  gold_file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: logs/gold_layer.log

loggers:
  data_pipeline:
    level: INFO
    handlers:
      - console
      - data_pipeline_file
      - error_file
    propagate: no

  data_pipeline_bronze:
    level: INFO
    handlers:
      - bronze_file
    propagate: no

  data_pipeline_silver:
    level: INFO
    handlers:
      - silver_file
    propagate: no

  data_pipeline_gold:
    level: INFO
    handlers:
      - gold_file
    propagate: no

root:
  level: ERROR
  handlers:
    - error_file